[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions."notify_expiring_certificates"]
  schedule = "0 9 * * *" # κάθε μέρα στις 09:00 UTC (11:00 Ελλάδας)
