[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions."notify_expiring_certificates"]
  schedule = "0 9 * * *"

[[redirects]]
  from = "/reset-password"
  to = "/reset-password.html"
  status = 200
