[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions.environment]
  MAILERSEND_TOKEN = ""

[[redirects]]
  from = "/reset-password"
  to = "/reset-password.html"
  status = 200

[functions."notify_expiring_certificates-scheduled"]
  schedule = "0 9 * * *" # εκτέλεση κάθε μέρα 12:00 ώρα Ελλάδας

  [functions."notify_user_expiry-scheduled"]
schedule = "@daily"

