[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions."notify_expiring_certificates-scheduled"]
  schedule = "0 9 * * *" # 09:00 UTC = 12:00 ώρα Ελλάδας (καλοκαίρι)

[[redirects]]
  from = "/reset-password"
  to = "/reset-password.html"
  status = 200
