[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions.environment]
  MAILERSEND_API_KEY = ""
  SUPABASE_URL = ""
  SUPABASE_SERVICE_ROLE_KEY = ""

[[redirects]]
  from = "/reset-password"
  to = "/reset-password.html"
  status = 200

[functions."notify_expiring_certificates-scheduled"]
  schedule = "0 9 * * *"
