import { demoData } from './demoData.js';
import { locale } from '../shared/i18n.js';
import { openCertificateCreateDialog, openCertificateEditDialog } from '../components/certificateUi.js';
import { openPdfViewer } from '../core/pdfViewer.js';

const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]));
let certificates=structuredClone(demoData.organization.certificates);
let partners=structuredClone(demoData.organization.partners);
let currentView='overview';
let currentPartner=null;
let selected=new Set();

const META={overview:['Επισκόπηση','Πιστοποιητικά, συνεργάτες και εκκρεμότητες σε μία ενιαία εικόνα.'],certificates:['Πιστοποιητικά','Διαχείριση των πιστοποιητικών που ανήκουν στον οργανισμό σας.'],partners:['Συνεργάτες','Συνδέστε άλλους οργανισμούς και διαχειριστείτε μόνο τη μεταξύ σας σχέση.'],compliance:['Συμμόρφωση','Απαιτήσεις και κατάσταση συμμόρφωσης ανά σχέση συνεργασίας.'],settings:['Ρυθμίσεις','Στοιχεία οργανισμού και ασφάλεια λογαριασμού.'],'partner-detail':['Καρτέλα συνεργάτη','Στοιχεία οργανισμού, σχέση συνεργασίας και κοινόχρηστα πιστοποιητικά.']};
const badge=(status,label)=>`<span class="demo-badge demo-badge--${status}">${esc(label)}</span>`;
const kpi=(label,value,note,icon)=>`<article class="demo-kpi ct-card"><div class="demo-kpi__icon"><i data-lucide="${icon}"></i></div><div><div class="demo-kpi__value">${value}</div><div class="demo-kpi__label">${esc(label)}</div><div class="demo-kpi__note">${esc(note)}</div></div></article>`;
const fmt=d=>d?new Date(d).toLocaleDateString(locale()):'—';
const statusLabel=s=>s==='soon'?'Προς λήξη':s==='expired'?'Ληγμένο':'Ενεργό';
const partnerStatus=s=>s==='critical'?'Χρειάζεται ενέργεια':s==='attention'?'Παρακολούθηση':'Ενεργή σχέση';
const statusClass=s=>s==='critical'?'expired':s==='attention'?'soon':'active';
function normalize(c){return {...c,date:c.date||c.expires||'',issue_date:c.issue_date||c.issued||'',file_url:c.file_url||'/assets/demo-certificates/company-demo.pdf'};}
function syncBack(index,v){certificates[index]={...certificates[index],...v,expires:v.date||certificates[index].expires,issued:v.issue_date||certificates[index].issued};}
function setView(view){currentView=view;document.querySelectorAll('.demo-view').forEach(v=>v.classList.toggle('is-active',v.id===`view-${view}`));document.querySelectorAll('.demo-nav').forEach(b=>b.classList.toggle('is-active',b.dataset.view===view||(view==='partner-detail'&&b.dataset.view==='partners')));const [title,desc]=META[view]||META.overview;$('demoViewTitle').textContent=title;$('demoViewDescription').textContent=desc;renderHeadActions();window.lucide?.createIcons();}
function renderHeadActions(){const el=$('demoHeadActions');el.innerHTML=currentView==='partner-detail'?`<button class="ct-btn ct-btn-secondary ct-btn-sm" data-back-partners><i data-lucide="arrow-left"></i> Πίσω στους συνεργάτες</button>`:'';el.querySelector('[data-back-partners]')?.addEventListener('click',()=>setView('partners'));}
function renderOverview(){const soon=certificates.filter(c=>c.status==='soon').length,expired=certificates.filter(c=>c.status==='expired').length;$('demoKpis').innerHTML=[kpi('Πιστοποιητικά',certificates.length,'Δικά σας έγγραφα','badge-check'),kpi('Συνεργάτες',partners.length,'Συνδεδεμένοι οργανισμοί','users'),kpi('Προς λήξη',soon,'Χρειάζονται παρακολούθηση','clock-3'),kpi('Ληγμένα',expired,'Χρειάζονται ενέργεια','triangle-alert')].join('');const attention=certificates.filter(c=>c.status!=='active');$('demoAttention').innerHTML=attention.length?attention.map(c=>{const i=certificates.indexOf(c);return `<div class="demo-list-row${c.is_private?' demo-row--private':''}" data-overview-cert="${i}" tabindex="0"><div class="demo-list-row__main"><div class="demo-file-icon"><i data-lucide="file-check-2"></i></div><div><strong>${esc(c.title)}</strong><small>${esc(c.type)} · Λήξη ${fmt(c.expires)}</small></div></div>${c.is_private?badge('neutral','Ιδιωτικό'):badge(c.status,statusLabel(c.status))}<i data-lucide="chevron-right"></i></div>`}).join(''):`<div class="demo-empty">Δεν υπάρχουν άμεσες εκκρεμότητες</div>`;$('demoPartnersOverview').innerHTML=partners.map((p,i)=>`<div class="demo-company-row ct-company-row--clickable" data-overview-partner="${i}" tabindex="0"><div class="demo-avatar">${esc(p.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2))}</div><div class="demo-company-row__main"><div><strong>${esc(p.name)}</strong><small>ΑΦΜ ${esc(p.afm)}</small></div></div>${badge(statusClass(p.status),partnerStatus(p.status))}<i data-lucide="chevron-right"></i></div>`).join('');document.querySelectorAll('[data-overview-cert]').forEach(r=>{r.onclick=()=>viewCertificate(+r.dataset.overviewCert);r.onkeydown=e=>{if(e.key==='Enter'){viewCertificate(+r.dataset.overviewCert)}}});document.querySelectorAll('[data-overview-partner]').forEach(r=>{r.onclick=()=>openPartner(+r.dataset.overviewPartner);r.onkeydown=e=>{if(e.key==='Enter'){openPartner(+r.dataset.overviewPartner)}}});}
function actionRail(i,c){return `<div class="demo-row-actions ct-row-actions"><button class="demo-icon-btn" data-action="view" data-index="${i}" title="Προβολή"><i data-lucide="eye"></i></button><button class="demo-icon-btn" data-action="edit" data-index="${i}" title="Επεξεργασία / αντικατάσταση PDF"><i data-lucide="pencil"></i></button><button class="demo-icon-btn" data-action="visibility" data-index="${i}" title="${c.is_private?'Κοινοποίηση σε συνεργάτες':'Απόκρυψη από συνεργάτες'}"><i data-lucide="${c.is_private?'eye':'eye-off'}"></i></button><button class="demo-icon-btn is-danger" data-action="delete" data-index="${i}" title="Διαγραφή"><i data-lucide="trash-2"></i></button></div>`;}
function filteredCertificates(){const q=($('demoCertSearch')?.value||'').toLowerCase();return certificates.map((c,i)=>({c,i})).filter(x=>`${x.c.title} ${x.c.type} ${x.c.certificate_number||''} ${x.c.issuer||''}`.toLowerCase().includes(q));}
function updateBulk(){const n=selected.size;$('demoSelectedCount').textContent=`${n} επιλεγμένα`;$('demoPrintSelected').disabled=!n;$('demoExportSelected').disabled=!n;const rows=filteredCertificates();const all=rows.length&&rows.every(({i})=>selected.has(i));$('demoSelectAll').checked=!!all;$('demoSelectAll').indeterminate=!all&&rows.some(({i})=>selected.has(i));}
function renderCertificates(){const rows=filteredCertificates();$('demoCertificates').innerHTML=rows.length?rows.map(({c,i})=>`<div class="demo-table-row${c.is_private?' demo-table-row--private':''}"><div class="demo-cert-check"><input type="checkbox" data-cert-check="${i}" ${selected.has(i)?'checked':''} aria-label="Επιλογή ${esc(c.title)}"></div><div class="demo-list-row__main"><div class="demo-file-icon"><i data-lucide="file-check-2"></i></div><div><strong>${esc(c.title)}</strong><small>${esc(c.certificate_number||c.owner||demoData.organization.name)}${c.is_private?' · Ιδιωτικό':''}</small></div></div><span>${esc(c.type)}</span><span>${fmt(c.expires)}</span>${badge(c.status,statusLabel(c.status))}${actionRail(i,c)}</div>`).join(''):`<div class="demo-empty">Δεν βρέθηκαν πιστοποιητικά</div>`;document.querySelectorAll('[data-cert-check]').forEach(cb=>cb.onchange=()=>{const i=+cb.dataset.certCheck;cb.checked?selected.add(i):selected.delete(i);updateBulk()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const i=+b.dataset.index;if(b.dataset.action==='view')viewCertificate(i);if(b.dataset.action==='edit')editCertificate(i);if(b.dataset.action==='visibility')toggleCertificateVisibility(i);if(b.dataset.action==='delete')deleteCertificate(i)});updateBulk();window.lucide?.createIcons();}
function renderPartners(){const q=($('demoPartnerSearch')?.value||'').toLowerCase();const rows=partners.map((p,i)=>({p,i})).filter(x=>`${x.p.name} ${x.p.afm} ${x.p.email}`.toLowerCase().includes(q));$('demoPartners').innerHTML=rows.length?rows.map(({p,i})=>`<div class="demo-company-row ct-company-row--clickable" data-demo-partner="${i}" tabindex="0" role="link"><div class="demo-avatar">${esc(p.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2))}</div><div class="demo-company-row__main"><div><strong>${esc(p.name)}</strong><small>ΑΦΜ ${esc(p.afm)} · ${esc(p.email)}</small></div></div><div class="demo-score"><div class="demo-score__bar"><i style="width:${p.score}%"></i></div><span>${p.score}%</span></div>${badge(statusClass(p.status),partnerStatus(p.status))}<i data-lucide="chevron-right"></i></div>`).join(''):`<div class="demo-empty">Δεν βρέθηκαν συνεργάτες</div>`;document.querySelectorAll('[data-demo-partner]').forEach(r=>{r.onclick=()=>openPartner(+r.dataset.demoPartner);r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPartner(+r.dataset.demoPartner)}}});window.lucide?.createIcons();}
function partnerCertificates(p){const file_url='/assets/demo-certificates/supplier-demo.pdf';const base=[{title:'ISO 9001:2015',type:'ISO 9001',expires:'2027-06-19',status:'active',file_url},{title:'ISO 13485:2016',type:'ISO 13485',expires:'2026-10-18',status:p.status==='attention'?'soon':'active',file_url},{title:'CE Documentation',type:'CE',expires:'2028-04-30',status:'active',file_url},{title:'Operating License',type:'Operating License',expires:'2027-12-31',status:'active',file_url}];if(p.status==='critical')base.push({title:'ISO 14001:2015',type:'ISO 14001',expires:'2026-07-15',status:'expired',file_url});return base.slice(0,Math.min(base.length,Math.max(3,p.certs||4)));}
function openPartner(index){currentPartner=partners[index];if(!currentPartner)return;const pcs=partnerCertificates(currentPartner);$('demoPartnerDetail').innerHTML=`<div class="demo-partner-detail-head"><div class="demo-avatar">${esc(currentPartner.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2))}</div><div class="demo-partner-detail-head__main"><h2>${esc(currentPartner.name)}</h2><p>ΑΦΜ ${esc(currentPartner.afm)} · ${esc(currentPartner.email)}</p></div>${badge(statusClass(currentPartner.status),partnerStatus(currentPartner.status))}</div><div class="demo-partner-detail-body"><section class="demo-panel"><div class="demo-panel__head"><div><h2>Στοιχεία συνεργάτη</h2><p>Ο οργανισμός δεν διαγράφεται από την πλατφόρμα όταν λήξει η συνεργασία.</p></div></div><div class="demo-detail-meta"><dl><div><dt>Επωνυμία</dt><dd>${esc(currentPartner.name)}</dd></div><div><dt>ΑΦΜ</dt><dd>${esc(currentPartner.afm)}</dd></div><div><dt>Email</dt><dd>${esc(currentPartner.email)}</dd></div><div><dt>Κατάσταση σχέσης</dt><dd>${esc(partnerStatus(currentPartner.status))}</dd></div><div><dt>Κάλυψη</dt><dd>${currentPartner.score}%</dd></div></dl><button class="ct-btn ct-btn-danger ct-btn-sm demo-relation-remove" id="demoRemoveRelation"><i data-lucide="unlink"></i> Κατάργηση συνεργασίας</button></div></section><section class="demo-panel"><div class="demo-panel__head"><div><h2>Κοινόχρηστα πιστοποιητικά</h2><p>Μόνο προβολή των πιστοποιητικών που έχει κοινοποιήσει ο συνεργάτης.</p></div></div><div class="demo-scroll-list">${pcs.map((c,i)=>`<div class="demo-list-row ct-company-row--clickable" data-partner-cert="${i}" tabindex="0"><div class="demo-list-row__main"><div class="demo-file-icon"><i data-lucide="file-check-2"></i></div><div><strong>${esc(c.title)}</strong><small>${esc(c.type)} · Λήξη ${fmt(c.expires)}</small></div></div>${badge(c.status,statusLabel(c.status))}<i data-lucide="chevron-right"></i></div>`).join('')}</div></section></div>`;document.querySelectorAll('[data-partner-cert]').forEach(r=>{r.onclick=()=>viewPartnerCertificate(pcs[+r.dataset.partnerCert]);r.onkeydown=e=>{if(e.key==='Enter')viewPartnerCertificate(pcs[+r.dataset.partnerCert])}});$('demoRemoveRelation').onclick=()=>removeRelationship(index);setView('partner-detail');window.lucide?.createIcons();}
async function viewPartnerCertificate(c){await openPdfViewer(c.file_url,c.title);}
async function viewCertificate(index){const c=certificates[index];if(!c)return;await openPdfViewer(c.preview_url||c.file_url||'/assets/demo-certificates/company-demo.pdf',c.title);}
async function createCertificate(){const r=await openCertificateCreateDialog({allowVisibility:true});if(!r.isConfirmed)return;const {file,...v}=r.value;const url=file?URL.createObjectURL(file):'/assets/demo-certificates/company-demo.pdf';certificates.unshift({title:v.title,type:v.type,certificate_number:v.certificate_number,issued:v.issue_date,issue_date:v.issue_date,expires:v.date,date:v.date,issuer:v.issuer,notes:v.notes,is_private:v.is_private,status:'active',owner:demoData.organization.name,file_url:url,preview_url:url,name:file?.name||'demo.pdf'});selected=new Set();renderAll();}
async function editCertificate(index){const c=certificates[index];if(!c)return;const r=await openCertificateEditDialog(normalize(c),{allowVisibility:true,allowFile:true});if(!r.isConfirmed)return;const {file,...v}=r.value;if(file){if(String(c.preview_url||'').startsWith('blob:'))URL.revokeObjectURL(c.preview_url);v.preview_url=URL.createObjectURL(file);v.file_url=v.preview_url;v.name=file.name;}syncBack(index,v);renderAll();await Swal.fire('Αποθηκεύτηκε',file?'Τα στοιχεία και το PDF αντικαταστάθηκαν στο demo session.':'Οι αλλαγές αποθηκεύτηκαν στο demo session.','success');}
async function toggleCertificateVisibility(index){const c=certificates[index];if(!c)return;const makePrivate=!c.is_private;const r=await Swal.fire({title:makePrivate?'Απόκρυψη από συνεργάτες;':'Κοινοποίηση σε συνεργάτες;',text:makePrivate?'Ολόκληρη η εγγραφή θα επισημανθεί ως ιδιωτική και δεν θα εμφανίζεται στους συνεργάτες.':'Το πιστοποιητικό θα εμφανίζεται ξανά στους ενεργούς συνεργάτες.',icon:'question',showCancelButton:true,confirmButtonText:makePrivate?'Απόκρυψη':'Κοινοποίηση',cancelButtonText:'Ακύρωση'});if(!r.isConfirmed)return;c.is_private=makePrivate;renderAll();}
async function deleteCertificate(index){const c=certificates[index];if(!c)return;const r=await Swal.fire({title:'Διαγραφή πιστοποιητικού;',text:c.title,icon:'warning',showCancelButton:true,confirmButtonText:'Διαγραφή',cancelButtonText:'Ακύρωση'});if(!r.isConfirmed)return;if(String(c.preview_url||'').startsWith('blob:'))URL.revokeObjectURL(c.preview_url);certificates.splice(index,1);selected=new Set();renderAll();}
async function removeRelationship(index){const p=partners[index];if(!p)return;const r=await Swal.fire({title:'Κατάργηση συνεργασίας;',text:`Θα διαγραφεί μόνο η σχέση με ${p.name}. Ο οργανισμός και τα πιστοποιητικά του παραμένουν στην πλατφόρμα.`,icon:'warning',showCancelButton:true,confirmButtonText:'Κατάργηση σχέσης',cancelButtonText:'Ακύρωση'});if(!r.isConfirmed)return;partners.splice(index,1);currentPartner=null;renderAll();setView('partners');}
function printSelected(){const rows=[...selected].sort((a,b)=>a-b).map(i=>certificates[i]).filter(Boolean);if(!rows.length)return;const w=window.open('','_blank','noopener,noreferrer');if(!w)return;w.document.write(`<html><head><title>CertiTrack</title><style>body{font-family:Arial;padding:24px}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:left;font-size:12px}</style></head><body><h2>Επιλεγμένα πιστοποιητικά</h2><table><tr><th>Τίτλος</th><th>Τύπος</th><th>Λήξη</th><th>Ορατότητα</th></tr>${rows.map(c=>`<tr><td>${esc(c.title)}</td><td>${esc(c.type)}</td><td>${fmt(c.expires)}</td><td>${c.is_private?'Ιδιωτικό':'Σε συνεργάτες'}</td></tr>`).join('')}</table><script>onload=()=>print()<\/script></body></html>`);w.document.close();}
function exportSelected(){const rows=[...selected].sort((a,b)=>a-b).map(i=>certificates[i]).filter(Boolean);if(!rows.length)return;const csv='\uFEFF'+['Τίτλος;Τύπος;Αριθμός;Έκδοση;Λήξη;Φορέας;Ορατότητα',...rows.map(c=>[c.title,c.type,c.certificate_number||'',c.issued||'',c.expires||'',c.issuer||'',c.is_private?'Ιδιωτικό':'Σε συνεργάτες'].map(v=>`"${String(v).replaceAll('"','""')}"`).join(';'))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='certitrack-selected-certificates.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function renderCompliance(){const compliant=partners.filter(p=>p.status==='compliant').length,attention=partners.filter(p=>p.status==='attention').length,critical=partners.filter(p=>p.status==='critical').length;$('demoComplianceKpis').innerHTML=[kpi('Συνεργάτες',partners.length,'Συνδεδεμένοι οργανισμοί','users'),kpi('Συμμορφωμένοι',compliant,'Πλήρεις απαιτήσεις','shield-check'),kpi('Χρειάζονται ενέργεια',attention+critical,'Παρακολούθηση','triangle-alert'),kpi('Μη συμμορφωμένοι',critical,'Ελλείψεις ή ληγμένα','circle-x')].join('');$('demoCompliance').innerHTML=partners.map((p,i)=>`<div class="demo-company-row ct-company-row--clickable" data-compliance-view="${i}" tabindex="0"><div class="demo-avatar">${esc(p.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2))}</div><div class="demo-company-row__main"><div><strong>${esc(p.name)}</strong><small>ΑΦΜ ${esc(p.afm)}</small></div></div><div class="demo-score"><div class="demo-score__bar"><i style="width:${p.score}%"></i></div><span>${p.score}%</span></div>${badge(statusClass(p.status),partnerStatus(p.status))}<i data-lucide="chevron-right"></i></div>`).join('');document.querySelectorAll('[data-compliance-view]').forEach(r=>r.onclick=()=>openPartner(+r.dataset.complianceView));}
function renderSettings(){$('demoSettingName').value=demoData.organization.name;$('demoSettingAfm').value=demoData.organization.afm;}
function renderAll(){renderOverview();renderCertificates();renderPartners();renderCompliance();renderSettings();window.lucide?.createIcons();}
function bind(){document.querySelectorAll('.demo-nav').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));$('demoCertSearch').addEventListener('input',renderCertificates);$('demoPartnerSearch').addEventListener('input',renderPartners);$('demoAddCert').onclick=createCertificate;$('demoSelectAll').onchange=()=>{const rows=filteredCertificates();if($('demoSelectAll').checked)rows.forEach(({i})=>selected.add(i));else rows.forEach(({i})=>selected.delete(i));renderCertificates()};$('demoPrintSelected').onclick=printSelected;$('demoExportSelected').onclick=exportSelected;$('demoAddPartner').onclick=()=>Swal.fire('Demo λειτουργία','Στην κανονική εφαρμογή γίνεται αναζήτηση οργανισμού και αποστολή αιτήματος συνεργασίας.','info');$('demoSettingsForm').onsubmit=e=>{e.preventDefault();demoData.organization.name=$('demoSettingName').value.trim()||demoData.organization.name;$('demoOrgSideName').textContent=demoData.organization.name;Swal.fire('Αποθηκεύτηκε','Η αλλαγή ισχύει μόνο στο demo session.','success')};$('demoPasswordBtn').onclick=e=>{e.preventDefault();Swal.fire('Demo λειτουργία','Η αλλαγή κωδικού είναι διαθέσιμη στην κανονική εφαρμογή.','info')};$('demoDeleteAccount').onclick=e=>{e.preventDefault();Swal.fire({title:'Αποχώρηση από το CertiTrack',text:'Αυτή είναι διαφορετική ενέργεια από την κατάργηση μιας συνεργασίας και αφορά μόνο τον ίδιο τον οργανισμό.',icon:'info',confirmButtonText:'ΟΚ'})};window.addEventListener('ct:languagechange',()=>renderAll());}
document.addEventListener('DOMContentLoaded',()=>{renderAll();bind();setView('overview');});
