import { demoData } from '../../demo/demoData.js';
import { adminService } from '../../services/adminService.js';
import { requirePlatformAdmin, statusKey, statusLabel, initials } from './adminCommon.js';
import { adminStatus, emptyState, kpiCard } from '../../components/uiPrimitives.js';
function renderStats(stats){const items=[['Οργανισμοί',stats.organizations||0,'building-2'],['Ενεργές συνεργασίες',stats.activeRelationships||0,'link-2'],['Εκκρεμή αιτήματα',stats.pendingRelationships||0,'clock-3'],['Πιστοποιητικά',stats.certificates||0,'badge-check']];document.getElementById('adminStats').innerHTML=items.map(([label,value,icon])=>kpiCard({label,value,icon,meta:'Στην πλατφόρμα'})).join('');}
function renderOrganizations(rows){const mount=document.getElementById('recentOrganizations');mount.innerHTML=rows.slice(0,7).map(o=>{const key=statusKey(o);return `<div class="ct-admin-list__row"><div class="ct-admin-org"><div class="ct-admin-avatar">${initials(o.name)}</div><div><strong>${o.name||'—'}</strong><small>Οργανισμός · ${o.afm||'—'}</small></div></div>${adminStatus(key==='active'?'success':key==='pending'?'warning':key==='blocked'?'danger':'neutral',statusLabel(key))}</div>`}).join('')||emptyState({title:'Δεν υπάρχουν οργανισμοί.'});}
function renderAudit(rows){const mount=document.getElementById('recentAudit');mount.innerHTML=rows.slice(0,6).map(x=>`<div class="ct-admin-activity__item"><strong>${x.action}</strong><p>${x.organization||x.entity||'Platform'} · ${x.when||'—'}</p></div>`).join('')||emptyState({title:'Δεν υπάρχει πρόσφατη δραστηριότητα.'});}
async function loadReal(){const [o,r,c,a]=await Promise.all([adminService.listOrganizations(),adminService.listRelationships(),adminService.listCertificates(),adminService.audit().select('*').order('created_at',{ascending:false}).limit(8)]);const firstError=[o,r,c,a].find(x=>x.error)?.error;if(firstError)throw firstError;const organizations=[...(o.data||[])].sort((a,b)=>new Date(b.created_at||b.timestamp||0)-new Date(a.created_at||a.timestamp||0));const relationships=r.data||[];const audit=(a.data||[]).map(x=>({action:x.action||'Activity',entity:x.entity_type,organization:'Οργανισμός',when:new Date(x.created_at).toLocaleString()}));return {stats:{organizations:organizations.length,activeRelationships:relationships.filter(x=>(x.status||x.access)==='active'||x.access==='granted').length,pendingRelationships:relationships.filter(x=>x.status==='pending').length,certificates:c.data?.length||0},organizations,audit};}
async function init(){const guard=await requirePlatformAdmin();if(guard.denied)return;try{if(guard.demo){const d=demoData.admin;renderStats({organizations:d.organizations.length,activeRelationships:18,pendingRelationships:3,certificates:438});renderOrganizations(d.organizations.map((x,i)=>({...x,afm:`09990${String(i+1).padStart(4,'0')}`})));renderAudit([{action:'Ανανέωση πιστοποιητικού',organization:'MedSupply A.E.',when:'Πριν 18 λεπτά'},{action:'Νέα σχέση συνεργασίας',organization:'CleanCare Services',when:'Σήμερα'},{action:'Αλλαγή ορατότητας εγγράφου',organization:'BioLab Solutions',when:'Σήμερα'}]);}else{const data=await loadReal();renderStats(data.stats);renderOrganizations(data.organizations);renderAudit(data.audit);}}catch(err){console.error(err);document.getElementById('recentOrganizations').innerHTML=emptyState({title:'Η admin πρόσβαση στα tenant δεδομένα δεν είναι ακόμη ενεργοποιημένη από RLS.'});renderStats({});renderAudit([]);}window.lucide?.createIcons();}
init();
